version: '3.9'
services:
  linda_trade_mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: linda-trade-mysql-container
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: ${MYSQL_DBNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
      - ./dbdata/struct:/docker-entrypoint-initdb.d
