CREATE TABLE `swap_price` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '唯一标识ID',
  `symbol` varchar(255) NOT NULL COMMENT '交易对符号，例如 BTC/USD',
  `last` float NOT NULL COMMENT '最新成交价格',
  `bid` float DEFAULT NULL COMMENT '买价',
  `ask` float DEFAULT NULL COMMENT '卖价',
  `high` float DEFAULT NULL COMMENT '24小时最高价',
  `low` float DEFAULT NULL COMMENT '24小时最低价',
  `timestamp` bigint DEFAULT NULL COMMENT 'Unix时间戳，记录价格时间',
  `datetime` varchar(255) DEFAULT NULL COMMENT '日期时间的字符串表示',
  `type` int DEFAULT NULL COMMENT '数据类型标识，1 表示有效数据',
  `status` int DEFAULT NULL COMMENT '状态标识，1 表示有效状态',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_symbol` (`symbol`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_datetime` (`datetime`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=534 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `option_chain` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `symbol` varchar(255) NOT NULL COMMENT '合约符号',
  `timestamp` bigint NOT NULL COMMENT '期权链最后更新的时间戳',
  `year` int NOT NULL COMMENT '年',
  `month` int NOT NULL COMMENT '月',
  `day` int NOT NULL COMMENT '日',
  `expiration_date` int NOT NULL DEFAULT '0',
  `strike` float NOT NULL COMMENT '行权价格',
  `option_type` char(1) NOT NULL COMMENT '行权方向，P 或 C',
  `bid_price` float DEFAULT NULL COMMENT '买价',
  `bid_size` int DEFAULT NULL COMMENT '买量',
  `ask_price` float DEFAULT NULL COMMENT '卖价',
  `ask_size` int DEFAULT NULL COMMENT '卖量',
  `last_price` float DEFAULT NULL COMMENT '最新成交价',
  `last_size` int DEFAULT NULL COMMENT '最新成交量',
  `type` int DEFAULT '1' COMMENT '有效标志',
  `status` int DEFAULT '1' COMMENT '状态标志',
  PRIMARY KEY (`id`),
  UNIQUE KEY `symbol` (`symbol`),
  UNIQUE KEY `uniq_symbol` (`symbol`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_year` (`year`),
  KEY `idx_day` (`day`),
  KEY `idx_strike` (`strike`),
  KEY `idx_option_type` (`option_type`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_expiration_date` (`expiration_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 创建 create_orders 表
CREATE TABLE `okx_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `api_key` varchar(100) DEFAULT NULL,
  `inst_type` varchar(50) NOT NULL COMMENT '产品类型',
  `inst_id` varchar(100) NOT NULL COMMENT '产品 ID',
  `tgt_ccy` varchar(50) DEFAULT '' COMMENT '目标币种',
  `ccy` varchar(50) DEFAULT '' COMMENT '币种',
  `ord_id` varchar(100) NOT NULL COMMENT '订单 ID',
  `cl_ord_id` varchar(100) NOT NULL COMMENT '客户端订单 ID',
  `algo_cl_ord_id` varchar(100) DEFAULT '' COMMENT '算法订单客户端 ID',
  `algo_id` varchar(100) DEFAULT '' COMMENT '算法订单 ID',
  `tag` varchar(100) NOT NULL COMMENT '标签',
  `px` decimal(40,20) NOT NULL COMMENT '价格',
  `sz` decimal(40,20) NOT NULL COMMENT '数量',
  `notional_usd` decimal(40,20) NOT NULL COMMENT '名义价值（USD）',
  `ord_type` varchar(50) NOT NULL COMMENT '订单类型',
  `side` varchar(50) NOT NULL COMMENT '方向',
  `pos_side` varchar(50) NOT NULL COMMENT '持仓方向',
  `td_mode` varchar(50) NOT NULL COMMENT '交易模式',
  `acc_fill_sz` decimal(40,20) NOT NULL COMMENT '累计成交数量',
  `fill_notional_usd` decimal(40,20) DEFAULT NULL COMMENT '成交名义价值（USD）',
  `avg_px` decimal(40,20) NOT NULL COMMENT '平均成交价格',
  `state` varchar(50) NOT NULL COMMENT '订单状态',
  `lever` decimal(40,20) NOT NULL COMMENT '杠杆',
  `pnl` decimal(40,20) NOT NULL COMMENT '盈亏',
  `fee_ccy` varchar(50) NOT NULL COMMENT '手续费币种',
  `fee` decimal(40,20) NOT NULL COMMENT '手续费',
  `rebate_ccy` varchar(50) NOT NULL COMMENT '返佣币种',
  `rebate` decimal(40,20) NOT NULL COMMENT '返佣金额',
  `category` varchar(50) NOT NULL COMMENT '分类',
  `u_time` bigint NOT NULL COMMENT '更新时间',
  `c_time` bigint NOT NULL COMMENT '创建时间',
  `source` varchar(100) DEFAULT '' COMMENT '来源',
  `reduce_only` varchar(10) NOT NULL COMMENT '仅减仓',
  `cancel_source` varchar(100) DEFAULT '' COMMENT '取消来源',
  `quick_mgn_type` varchar(100) DEFAULT '' COMMENT '快速保证金类型',
  `stp_id` varchar(100) DEFAULT '' COMMENT 'STP ID',
  `stp_mode` varchar(50) NOT NULL COMMENT 'STP 模式',
  `attach_algo_cl_ord_id` varchar(100) DEFAULT '' COMMENT '附加算法订单客户端 ID',
  `last_px` decimal(40,20) NOT NULL COMMENT '最新价格',
  `is_tp_limit` varchar(10) NOT NULL COMMENT '是否为止盈限价单',
  `sl_trigger_px` decimal(40,20) DEFAULT NULL COMMENT '止损触发价格',
  `sl_trigger_px_type` varchar(50) DEFAULT '' COMMENT '止损触发价格类型',
  `tp_ord_px` decimal(40,20) DEFAULT NULL COMMENT '止盈订单价格',
  `tp_trigger_px` decimal(40,20) DEFAULT NULL COMMENT '止盈触发价格',
  `tp_trigger_px_type` varchar(50) DEFAULT '' COMMENT '止盈触发价格类型',
  `sl_ord_px` decimal(40,20) DEFAULT NULL COMMENT '止损订单价格',
  `fill_px` decimal(40,20) DEFAULT NULL COMMENT '成交价格',
  `trade_id` varchar(100) DEFAULT '' COMMENT '成交 ID',
  `fill_sz` decimal(40,20) NOT NULL COMMENT '成交数量',
  `fill_time` bigint DEFAULT NULL COMMENT '成交时间',
  `fill_pnl` decimal(40,20) NOT NULL COMMENT '成交盈亏',
  `fill_fee` decimal(40,20) NOT NULL COMMENT '成交手续费',
  `fill_fee_ccy` varchar(50) DEFAULT '' COMMENT '成交手续费币种',
  `exec_type` varchar(50) DEFAULT '' COMMENT '执行类型',
  `fill_px_vol` decimal(40,20) DEFAULT NULL COMMENT '成交价格波动',
  `fill_px_usd` decimal(40,20) DEFAULT NULL COMMENT '成交价格（USD）',
  `fill_mark_vol` decimal(40,20) DEFAULT NULL COMMENT '成交标记波动',
  `fill_fwd_px` decimal(40,20) DEFAULT NULL COMMENT '成交远期价格',
  `fill_mark_px` decimal(40,20) DEFAULT NULL COMMENT '成交标记价格',
  `amend_source` varchar(100) DEFAULT '' COMMENT '修改来源',
  `req_id` varchar(100) DEFAULT '' COMMENT '请求 ID',
  `amend_result` varchar(100) DEFAULT '' COMMENT '修改结果',
  `code` varchar(50) NOT NULL COMMENT '状态码',
  `msg` varchar(255) DEFAULT '' COMMENT '消息',
  `px_type` varchar(50) NOT NULL COMMENT '价格类型',
  `px_usd` decimal(40,20) NOT NULL COMMENT '价格（USD）',
  `px_vol` decimal(40,20) NOT NULL COMMENT '价格波动',
  `linked_algo_ord_algo_id` varchar(100) DEFAULT '' COMMENT '关联算法订单 ID',
  `attach_algo_ords` text COMMENT '附加算法订单列表',
  PRIMARY KEY (`id`),
  KEY `idx_ord_id` (`ord_id`),
  KEY `idx_cl_ord_id` (`cl_ord_id`),
  KEY `idx_inst_id` (`inst_id`),
  KEY `idx_state` (`state`),
  KEY `idx_c_time` (`c_time`),
  KEY `idx_u_time` (`u_time`),
  KEY `idx_px` (`px`),
  KEY `idx_sz` (`sz`),
  KEY `idx_notional_usd` (`notional_usd`),
  KEY `idx_avg_px` (`avg_px`),
  KEY `idx_pnl` (`pnl`),
  KEY `idx_px_usd` (`px_usd`),
  KEY `idx_px_vol` (`px_vol`),
  KEY `idx_api_key` (`api_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='创建订单表';

-- 市场品种元数据（非破坏性新增）
CREATE TABLE IF NOT EXISTS `market_symbol_meta` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `exchange` varchar(64) NOT NULL COMMENT '交易所标识，例如 okx、binance',
  `symbol` varchar(255) NOT NULL COMMENT '交易所原生符号，例如 BTC/USDT, BTC/USDT:USDT',
  `base` varchar(64) DEFAULT NULL COMMENT '基础货币，例如 BTC',
  `quote` varchar(64) DEFAULT NULL COMMENT '计价货币，例如 USDT',
  `market_type` varchar(32) NOT NULL DEFAULT 'spot' COMMENT '市场类型：spot/swap/futures/index',
  `first_seen_ts` bigint DEFAULT NULL COMMENT '首次发现时间戳(ms)',
  `last_seen_ts` bigint DEFAULT NULL COMMENT '最近发现时间戳(ms)',
  `is_active` tinyint DEFAULT '1' COMMENT '是否活跃',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_exchange_symbol` (`exchange`,`symbol`),
  KEY `idx_exchange` (`exchange`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_market_type` (`market_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='市场品种元数据表';

-- 日线级别 OHLCV（非破坏性新增）
CREATE TABLE IF NOT EXISTS `market_daily_ohlcv` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `exchange` varchar(64) NOT NULL COMMENT '交易所标识，例如 okx、binance',
  `symbol` varchar(255) NOT NULL COMMENT '交易所原生符号，例如 BTC/USDT',
  `base` varchar(64) DEFAULT NULL COMMENT '基础货币',
  `quote` varchar(64) DEFAULT NULL COMMENT '计价货币',
  `market_type` varchar(32) NOT NULL DEFAULT 'spot' COMMENT '市场类型：spot/swap/futures/index',
  `timeframe` varchar(16) NOT NULL DEFAULT '1d' COMMENT '时间粒度，固定 1d 便于扩展',
  `open` decimal(40,20) NOT NULL COMMENT '开盘价',
  `high` decimal(40,20) NOT NULL COMMENT '最高价',
  `low` decimal(40,20) NOT NULL COMMENT '最低价',
  `close` decimal(40,20) NOT NULL COMMENT '收盘价',
  `volume` decimal(40,20) DEFAULT NULL COMMENT '成交量（base 维度，如 BTC 数量）',
  `turnover` decimal(40,20) DEFAULT NULL COMMENT '成交额（quote 维度，如 USDT 金额）',
  `trades` bigint DEFAULT NULL COMMENT '成交笔数（若交易所提供）',
  `timestamp` bigint NOT NULL COMMENT 'K线时间戳(ms)，一般为日线起始时刻',
  `datetime` varchar(64) DEFAULT NULL COMMENT '日期字符串，例如 2025-01-01',
  `status` int DEFAULT '1' COMMENT '状态标志',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_exchange_symbol_tf_ts` (`exchange`,`symbol`,`timeframe`,`timestamp`),
  KEY `idx_exchange` (`exchange`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_market_type` (`market_type`),
  KEY `idx_timeframe` (`timeframe`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='日线级别 OHLCV 数据表';

